
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action CloseAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action dialogInfoAction;
	private global::Gtk.Action ViewAction;
	private global::Gtk.Action FontAction;
	private global::Gtk.Action ZoomInAction;
	private global::Gtk.Action ZoomOutAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar1;
	private global::Gtk.HPaned hpaned1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Entry entrySearch;
	private global::Gtk.Button buttonSearch;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TreeView treeviewclasses;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.ScrolledWindow scrolledwindow1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label label2;
	private global::Gtk.ComboBox comboboxLanguage;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView textviewCode;
	private global::Gtk.Statusbar statusbar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("_File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_File");
		w1.Add (this.FileAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("_Open"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Open");
		w1.Add (this.openAction, null);
		this.CloseAction = new global::Gtk.Action ("CloseAction", global::Mono.Unix.Catalog.GetString ("_Close"), null, null);
		this.CloseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Close");
		w1.Add (this.CloseAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Exit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Exit");
		w1.Add (this.quitAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("_Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Help");
		w1.Add (this.HelpAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("_About"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_About");
		w1.Add (this.dialogInfoAction, null);
		this.ViewAction = new global::Gtk.Action ("ViewAction", global::Mono.Unix.Catalog.GetString ("View"), null, null);
		this.ViewAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View");
		w1.Add (this.ViewAction, null);
		this.FontAction = new global::Gtk.Action ("FontAction", global::Mono.Unix.Catalog.GetString ("Font"), null, null);
		this.FontAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Font");
		w1.Add (this.FontAction, null);
		this.ZoomInAction = new global::Gtk.Action ("ZoomInAction", global::Mono.Unix.Catalog.GetString ("Zoom _In"), null, null);
		this.ZoomInAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zoom _In");
		w1.Add (this.ZoomInAction, "<Primary><Mod2>KP_Add");
		this.ZoomOutAction = new global::Gtk.Action ("ZoomOutAction", global::Mono.Unix.Catalog.GetString ("Zoom _Out"), null, null);
		this.ZoomOutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Zoom _Out");
		w1.Add (this.ZoomOutAction, "<Primary><Mod2>KP_Subtract");
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Dex Disassembler");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='CloseAction' action='CloseAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='ZoomInAction' action='ZoomInAction'/><menuitem name='ZoomOutAction' action='ZoomOutAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='dialogInfoAction' action='dialogInfoAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 190;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entrySearch = new global::Gtk.Entry ();
		this.entrySearch.CanFocus = true;
		this.entrySearch.Name = "entrySearch";
		this.entrySearch.IsEditable = true;
		this.entrySearch.ActivatesDefault = true;
		this.entrySearch.InvisibleChar = '●';
		this.hbox1.Add (this.entrySearch);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entrySearch]));
		w3.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonSearch = new global::Gtk.Button ();
		this.buttonSearch.CanDefault = true;
		this.buttonSearch.CanFocus = true;
		this.buttonSearch.Name = "buttonSearch";
		this.buttonSearch.UseUnderline = true;
		this.buttonSearch.Label = global::Mono.Unix.Catalog.GetString ("Search");
		this.hbox1.Add (this.buttonSearch);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSearch]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(5));
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(5));
		this.GtkAlignment1.TopPadding = ((uint)(3));
		this.GtkAlignment1.RightPadding = ((uint)(5));
		this.GtkAlignment1.BottomPadding = ((uint)(3));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeviewclasses = new global::Gtk.TreeView ();
		this.treeviewclasses.CanFocus = true;
		this.treeviewclasses.Name = "treeviewclasses";
		this.treeviewclasses.HeadersVisible = false;
		this.GtkScrolledWindow.Add (this.treeviewclasses);
		this.GtkAlignment1.Add (this.GtkScrolledWindow);
		this.frame4.Add (this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Classes</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel4;
		this.vbox3.Add (this.frame4);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame4]));
		w9.Position = 1;
		this.hpaned1.Add (this.vbox3);
		global::Gtk.Paned.PanedChild w10 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox3]));
		w10.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w11 = new global::Gtk.Viewport ();
		w11.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Language:");
		this.hbox2.Add (this.label2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.comboboxLanguage = new global::Gtk.ComboBox ();
		this.comboboxLanguage.CanFocus = true;
		this.comboboxLanguage.Name = "comboboxLanguage";
		this.hbox2.Add (this.comboboxLanguage);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.comboboxLanguage]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.textviewCode = new global::Gtk.TextView ();
		this.textviewCode.CanFocus = true;
		this.textviewCode.Name = "textviewCode";
		this.textviewCode.Editable = false;
		this.textviewCode.PixelsBelowLines = 5;
		this.GtkScrolledWindow1.Add (this.textviewCode);
		this.vbox2.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
		w16.Position = 1;
		w11.Add (this.vbox2);
		this.scrolledwindow1.Add (w11);
		this.hpaned1.Add (this.scrolledwindow1);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w20.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar = new global::Gtk.Statusbar ();
		this.statusbar.Name = "statusbar";
		this.statusbar.Spacing = 6;
		this.statusbar.HasResizeGrip = false;
		this.vbox1.Add (this.statusbar);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar]));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 724;
		this.DefaultHeight = 471;
		this.buttonSearch.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.CloseAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
		this.quitAction.Activated += new global::System.EventHandler (this.OnExitActionActivated);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.ZoomInAction.Activated += new global::System.EventHandler (this.OnZoomIn);
		this.ZoomOutAction.Activated += new global::System.EventHandler (this.OnZoomOut);
		this.buttonSearch.Clicked += new global::System.EventHandler (this.OnButtonSearchClicked);
		this.comboboxLanguage.Changed += new global::System.EventHandler (this.LanguageChanged);
	}
}
